### ISSUE TITLE
Parallel computation of gradient

### ISSUE THREAD

**Issue by alexvoronov** [autodiff/autodiff#118]
Hi, 

First of all, thanks for the autodiff library: header-only and works with Eigen make it easy to use.

I have a question: is there a way to calculate gradient in parallel on a multi-core machine? (scalar function, vector argument, forward mode).

I was looking at [`gradient` function](https://github.com/autodiff/autodiff/blob/8e9fbb96a0048dd52e93e1882040716ade92edbb/autodiff/forward/eigen.hpp#L200-L222), would it be possible to change the loops to use `std::for_each` or `std::transform` that allow flexible `ExecutionPolicy`?

**Comment by alexvoronov** [comment]
I have realised that `gradient` function mutates elements of the argument vector: [`w[j].grad = 1.0;`](https://github.com/autodiff/autodiff/blob/8e9fbb96a0048dd52e93e1882040716ade92edbb/autodiff/forward/eigen.hpp#L212) .

It looks like to run in parallel, it would be necessary to copy the whole `w` to compute the derivative wrt each element of `w`.

**Comment by allanleal** [comment]
Hi @alexvoronov . I have not explored this possibility yet. In my applications, which require constrained numerical optimization calculations, it makes more sense to parallelize the solution of multiple computations, instead of what happens inside each of them (e.g. parallel computation of the Hessian matrix). But being able to accomplish this might be needed if many variables are considered.

> I have realised that gradient function mutates elements of the argument vector: `w[j].grad = 1.0;` .

This is needed to propagate the derivative calculations with respect to the seeded variable (`: `w[j].grad = 1.0` while : `w[i].grad = 0.0;` for all `i != j` means derivative with respect to variable `j` is to be propagated). 

> It looks like to run in parallel, it would be necessary to copy the whole w to compute the derivative wrt each element of w.

Yes, each parallel process or thread will have to its own copy of the input vector. I don't think this should be an issue in the most cases. If it is, because of memory, forget above further higher-order derivatives (e.g. Hessian)! ;)

**Comment by alexvoronov** [comment]
I'm looking into using autodiff for steered molecular dynamics, where an extra force [twists a DNA molecule](https://github.com/annareym/DNA_Deformation_Toolkit). It looks like the way this extra force is [implemented](https://www.plumed.org/) is by "freezing" parallel MD, calculating force and derivatives, and then resuming MD. So speeding up gradient calculation might give an overall speedup.

**Comment by alexvoronov** [comment]
Here is my take on implementing parallel computation of the gradient, in case someone finds this discussion later. The gradient is calculated for function `f(x)` wrt all elements of the vector `x`, at the point `x=x0`:

```c++
template <int N_COORDS>
static inline std::tuple<double,Eigen::Matrix<double,N_COORDS,1>> 
valueAndGradient(const Eigen::Matrix<double,N_COORDS,1> &x0) {
    // Eigen::Matrix does not support iteration inside std::transform, use another container.
    // Using std::array for the gradient. 
    // Change to std::vector if size is not known at compile time.
    std::array<double, N_COORDS> g;

    std::array<int, N_COORDS> idx;  // Index: a range from 0 to N_COORDS-1.
    std::iota(idx.begin(), idx.end(), 0);

    std::transform(std::execution::par, std::begin(idx), std::end(idx), std::begin(g), [=](auto j) {
        Eigen::Matrix<autodiff::dual, N_COORDS, 1> x(x0);
        x[j].grad = 1.0;
        // When I use std::apply, compiler complains. Changed to simple function call.
        // autodiff::dual u = std::apply(f<autodiff::dual, N_COORDS>, x);  // Compiler complains.
        autodiff::dual u = f(x);
        return u.grad;
        });
    double value = f(x0);
    Eigen::Matrix<double,N_COORDS,1> g_mtx(g.data());  // Gradient as Eigen::Matrix.
    return {value, g_mtx};
}
```

**Comment by allanleal** [comment]
Hi @alexvoronov - very nice! Thanks a lot for this. It should indeed be instructive for others with similar intents in the future.
