### ISSUE TITLE
Reverse Mode - Traversing Expression Tree

### ISSUE THREAD

**Issue by pwilliams-kxs** [autodiff/autodiff#131]
Hello,

I've been playing around with AutoDiff and I've been able to make the reverse mode differentiation work with some code I have. However I was wondering if it is possible to traverse the expression tree and how one would accomplish that.

My goal is to automatically detect all input and intermediate variables given only the output, so that I can procedurally get the derivatives of a function at various points in the function, without needed to know the structure of the function and/or the inputs before hand.

Thanks!

**Comment by allanleal** [comment]
Hi @pwilliams-kxs - would you please provide a simple example that illustrates what you need? This is not about a working code example! Just a piece of code that demonstrates what you want to achieve. 

Traversing the expression tree is possible because this is done to propagate the derivative calculations. Check the types `Expr`, `VariableExpr`, `ConstantExpr`, `UnaryExpr`, `BinaryExpr`, `MulExpr` (and any other that may help). Check how the `propagate` method is implemented for these types. This will give you an idea of how the expression tree is traversed. 

I think we should have a `visit` method that performs an action on every node of the expression tree. The `visit` method would then accept an `std::function` object as an argument.

I'm happy to hear and discuss alternative ideas though.

**Comment by pwilliams-kxs** [comment]
Ideally, doing something like depth-first or breadth-first traversal of the tree would be awesome.

for an example i'll just make up some simple function:

```
var exampleFunc(var* x, var* y){
    auto a = x * x;
    auto b = x + y;
    auto c = a / b;

    auto z = a + b + c;
    return z;
}
```

if i then invoke `z = f(x, y)`. I would really like to get the `derivatives(z, wrt(x, y, a, b, c)) ` but that's not possible since I don't have access to a,b,c outside of the function scope.

I was trying to do something similar to what you said with the visit method by doing something like casting z.expr to a BinaryExpr and then doing z.r and z.l to get the child nodes, but it seems like that's not quite the way to do it.

But to summarize, if there's a way that I can do a traversal of the expression tree so that I can get pointers to all of the internal variables so that I can automatically do `derivatives` with regards to all the internal variables, that would be all I would need.

**Comment by allanleal** [comment]
Interesting, I think you can achieve this in a much simpler and elegant way:

~~~c++
struct Props 
{
    var a;
    var b;
    var c;
    var z;
};

var exampleFunc(const var& x, const var& y)
{
    Props props;

    auto& [a, b, c, z] = props;

    a = x * x;
    b = x + y;
    c = a / b;
    z = a + b + c;

    return props;
}

auto props = exampleFunc(x, y);

const auto& [a, b, c, z] = props;

auto ds = derivatives(z, wrt(x, y, a, b, c));
~~~

It could be, however, that your `Props` definition has a `std::vector<var>`, should you not know at compile time the number of `var` objects computed in `exampleFunc`. 

On a separate note, why are you using `var*` as argument type and not `var&` or `const var&`?

**Comment by pwilliams-kxs** [comment]
My intent was to add in AutoDiff after the fact to a potentially large function without needing to change much of the internal code, but it seems like that might not be the right use case for AutoDiff as opposed to building a function with AutoDiff in mind from the start.

**Comment by allanleal** [comment]
I'll close this issue now, but happy to reopen again should the discussion restart.
