### ISSUE TITLE
AUTODIFF LIBRARY COMPILE ERROR WITH EIGEN LINEAR SYSTEMS SOLVER

### ISSUE THREAD

**Issue by George-Eric** [autodiff/autodiff#137]
Hi Allan:

Thank you for all your valuable work - autodiff C++ is central to the analytics library I am developing to compute market risk sensitivities of derivative instruments.

I am attempting to use autodiff C++ v0.5.11 in conjunction with Eigen 3.3.7 to solve a linear system of equations, but encounter a compilation error in VS2019 v16.7.2 on MS Windows that I cannot fix, and would appreciate your assistance.

Here is a small program that reproduces the issue:

#include <eigen3/Eigen/Core>
#include <eigen3/Eigen/Dense>
#include <autodiff/reverse.hpp>
#include <autodiff/reverse/eigen.hpp>
#include <autodiff/reverse/reverse.hpp>

int main()
{
   using namespace Eigen;
   using namespace autodiff;
   using namespace autodiff::reverse;

   // Solve Ax = b.
   // Solution: x = (3, 2, 1).
   Matrix<var, 3, 3> A;
   A << 1, 3, 3, // row 1
             1, 3. 4, // row 2
             1, 4, 3; // row 3
   Matrix<var, 3, 1> b;
   b << 12, 13, 14;
   const auto x = A.colPivHouseholderQr().solve(b);

   return 0;
}

%Compiler message%
error C2678: binary ‘<‘: no operator found which takes a left-hand  operator of type ‘autodiff::reverse::Variable<double>’ (or there is no acceptable conversion).
...

I have tried other methods available in Eigen, for example “jacobiSvd,” but encounter similar compilation errors.

I can see in <reverse.hpp> that you have overloaded the comparison operators, so I cannot see how to resolve the issue, and would value your assistance.

Kind regards,
George-Eric

**Comment by allanleal** [comment]
Hi George-Eric. Thanks for your feedback. I can confirm this also does not compile with gcc. Replacing `var` by `dual`, nevertheless works:

~~~c++
#include <eigen3/Eigen/Core>
#include <eigen3/Eigen/Dense>
#include <autodiff/reverse.hpp>
#include <autodiff/reverse/eigen.hpp>
#include <autodiff/reverse/reverse.hpp>
#include <autodiff/forward/forward.hpp>
#include <autodiff/forward/eigen.hpp>
#include <iostream>

int main()
{
    using namespace Eigen;
    using namespace autodiff;
    using namespace autodiff::reverse;

    // Solve Ax = b.
    // Solution: x = (3, 2, 1).
    Matrix<dual, 3, 3> A;
    A << 1, 3, 3, // row 1
         1, 3, 4, // row 2
         1, 4, 3; // row 3
    Matrix<dual, 3, 1> b;
    b << 12, 13, 14;

    const auto x = A.colPivHouseholderQr().solve(b);

    std::cout << x << std::endl;

    return 0;
}
// This prints: 3 2 1
~~~

I'll investigate was is missing in the implementation of `var` to get this working.

**Comment by allanleal** [comment]
Implementing the missing comparison operators for `var` was enough to resolve the compilation error here, using `gcc`. However, the output is not correct. 

I tried to test what would happen if `A` is composed of `double`, instead of `var`. The vector `b` is still composed of `var`. Eigen is not happy about the mixing of types, and several compilation errors are produced.

Tried to use LU, instead of ColPivHouseholderQr:

~~~cpp
Matrix<var, 3, 3> A;
A << 1, 0, 0, // row 1
     0, 2, 0, // row 2
     0, 0, 4; // row 3
Matrix<var, 3, 1> b;
b << 1, 4, 24;

const auto x = A.lu().solve(b);
~~~

But compilation is only possible if line 124 in Eigen header file `TriangularSolverMatrix.h` is changed from:

~~~cpp
Scalar a = (Mode & UnitDiag) ? Scalar(1) : Scalar(1)/conj(tri(i,i));
~~~

to 

~~~cpp
Scalar a = (Mode & UnitDiag) ? Scalar(1) : Scalar(Scalar(1)/conj(tri(i,i)));
~~~

otherwise operator `?` has two different return types, which produces a compilation error. 

Still, something is going on and the result is not correct (it should be `x = [1, 3, 6]`).

At the moment, I suggest you use `dual` instead, which works in all scenarios above. This does not solve the issue but should allow you to get going for now.

**Comment by allanleal** [comment]
Ok, I got it working with `var`. I'll give further details soon.

**Comment by George-Eric** [comment]
Hi Allan:

Thank you very much for your assistance!

Every time that I have requested assistance, you have been very responsive and provided excellent answers.

I confirm that the example I provided compiles with the type autodiff::dual, and provides correct answers. I tested: colPivHouseholdrQr and fullPivLu.

I also tested two other methods, bdcSvd and jacobiSvd, that use Singular Value Decomposition (SVD), rather than LU factorisation, to solve the linear system.  In both cases, the code compiles, but an assertion failure occurs at runtime when autodiff::dual is used. 

It would be useful to have access to the SVD functionality in Eigen, as it would allow me to compute the matrix pseudo inverse.

No problem for me, as a temporary workaround, to use the autodiff::dual type.

One issue that I have observed with the autodiff::dual type is that the intellisense/ code inspection tool in the VS2019 IDE creates false warnings: “copy constructor for class  “autodiff::forward::Dual<double, double>” is ambiguous”. I think a similar issue has been reported?

Look forward to seeing your solution as to how you resolved the Eigen solver issue when autodiff::var is used in reverse mode.

Kind regards,
George-Eric

**Comment by allanleal** [comment]
Hi George-Eric, I'm happy about solving these issues. I have not experienced them because in my use cases, I don't construct matrices with `var` or `dual`. I want to make sure though that this library is useful for other applications in which this is necessary (e.g., performing decompositions of matrices with `autodiff` types).

OK, I have created this PR #138 that implements the missing operators. With these changes, I'm able to compile and run successfully the following code:

~~~cpp
#include <iostream>
#include <eigen3/Eigen/Dense>
#include <autodiff/reverse.hpp>
#include <autodiff/reverse/eigen.hpp>
#include <autodiff/forward.hpp>
#include <autodiff/forward/eigen.hpp>

int main()
{
    using namespace Eigen;
    using namespace autodiff;

    // Solve Ax = b.
    // Solution: x = (3, 2, 1).
    Matrix<var, 3, 3> A;
    A << 1, 3, 3, // row 1
         1, 3, 4, // row 2
         1, 4, 3; // row 3
    Matrix<var, 3, 1> b;
    b << 12, 13, 14;

    // const auto x = A.colPivHouseholderQr().solve(b); // This does not work! x is an eigen expression instead of a vector. Dangling reference somewhere.
    const Matrix<var, 3, 1> x = A.colPivHouseholderQr().solve(b);

    std::cout << x << std::endl;

    return 0;
}
~~~

Note above the commented line `const auto x = ...`. This causes segfault - there is something going on that I could not identify yet, but it all seems to be the fact that `x` is an Eigen expression with dangling references at the point the expression is evaluated at `cout << x << endl;`.

So, as a rule of thumb, at least at this point, avoid using `auto x = A.someMatrixDecompositionMethod().solve(b)`. Instead, evaluate straightway the Eigen expression to avoid dangling references.

If instead, we do:

~~~cpp
ColPivHouseholderQR<Matrix<var, 3, 3>> qr;
qr.compute(A);

const auto x = qr.solve(b); // x is an expression with references to qr, which remains alive in the main scope
std::cout << x << std::endl; // x is evaluated to a vector correctly here - no segfault
~~~

This does not produce dangling references because the Eigen expression stored in `x` now has references to `qr`, which is available at that scope.

**Comment by allanleal** [comment]
> One issue that I have observed with the autodiff::dual type is that the intellisense/ code inspection tool in the VS2019 IDE creates false warnings: “copy constructor for class “autodiff::forward::Dual<double, double>” is ambiguous”. I think a similar issue has been reported?

I'm also facing this here using Visual Studio Code and it is quite annoying in fact. The code compiles and executes fine, but we get these error wiggles all over the place sometimes. I'll fix this at some point, but at this time I'm not able to. 

@benjaminhuth You have been fixing warning issues in `autodiff` for a while. Do you happen to use Visual Studio or Visual Studio Code? Do you have any idea why the intellisense gives these false errors?

**Comment by benjaminhuth** [comment]
@allanleal Unfortunately I've not used `autodiff` with these tools yet, only with gcc/clang based toolchains. But I will try to take a look onto this at the weekend.

**Comment by George-Eric** [comment]
Hi Allan:

Thank you for release v0.5.13; I will test it and get back to you asap with comments.

I have created the new issue you requested for the error in using autodiff with the Eigen SVD solvers.

Kind regards,
George-Eric

**Comment by George-Eric** [comment]
Hi Allan:

I have tested release v0.5.13, and confirm the fix that you have made is successful.

Thank you for your assistance.

Kind regards,
George-Eric

**Comment by allanleal** [comment]
Thanks, George-Eric. I still need to check your other issue.
