### ISSUE TITLE
Derivative of f(x) = sin^2(x) / x^2 at x = 0

### ISSUE THREAD

**Issue by sergeigribanov** [autodiff/autodiff#162]
Let us consider the function f(x) = sin^2(x) / x^2. It is easy to show that f'(0) = 0. But autodiff gives the answer f'(0) = nan (due to division zero by zero in derivatives). Is it possible to avoid this problem in this case? Is it possible to avoid the same problem in the case, when f(x) = h(x) / g(x), where h(x) and g(x) are some arbitrary functions (Taylor expansion for each of these functions exists).

**Comment by allanleal** [comment]
This would be possible if a symbolic algorithm was implemented so that we could simplify the intermediate derivative expressions. Since `autodiff` aims to be fast, for scientific computations, symbolic algorithm is not used. For a function:

![image](https://user-images.githubusercontent.com/5825588/182367800-495bc5f6-1023-4ed0-bc1c-926f2fc65154.png)

Its derivative will be computed using chain rule:

![image](https://user-images.githubusercontent.com/5825588/182367863-b4b031e2-69f9-46ac-ba4e-bc0108891d32.png)

The evaluations of `g(x)` and `h(x)` to compute `f(x)` would be reused in the computation of `f'(x)` for performance reasons. Thus if `h(x)` is zero at `x`, you'll get `nan`.

If performance is important in your application, but such situations occur sometimes, I recommend you introduce a check beforehand and compute the "singular point" yourself.
