### ISSUE TITLE
Not compiling when function input is Eigen::VectorXd

### ISSUE THREAD

**Issue by joao-pm-santos96** [autodiff/autodiff#283]
Hello!
First of all, thank you for this amazing library, is awesome in so many ways!

I am trying to use it in a special case: I have a function __f__ (which I cannot change) which only accepts Eigen::VectorXd as its input.
The issue is that when I try to compute the gradient of this function __f__ I received the following error:

```bash
/usr/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h:24:102: error: cannot convert ‘const autodiff::detail::Real<1, double>’ to ‘double’ in assignment
   24 |   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff(DstScalar& a, const SrcScalar& b) const { a = b; }
```

Is this expected or should I ba able to compile it? If this was to be expected, is there something I can do to fix it?

Here is an example which creates the mentioned error:

```cpp
#include <autodiff/forward/real.hpp>
#include <autodiff/forward/real/eigen.hpp>
using namespace autodiff;

#include <Eigen/Core>
#include <Eigen/Geometry>

double f(const Eigen::VectorXd& x)
{
  return (x * x).sum();
}

int main(int argc, char *argv[])
{
  autodiff::ArrayXreal x(5);
  x << 1, 2, 3, 4, 5;

  autodiff::real u;
  Eigen::VectorXd g = gradient(f, wrt(x), at(x), u);
}
```

**Comment by allanleal** [comment]
Hi @joao-pm-santos96 , thanks for your feedback. This is most likely happening because you have not activated implicit conversion from autodiff numbers to `double`. By default, you have to do conversions explicitly. 

Try define this before including autodiff header files::

~~~c++
define AUTODIFF_ENABLE_IMPLICIT_CONVERSION_REAL=1
~~~

or add this in your `CMakeList.txt` file:

~~~
target_compile_definitions(YourTargetName PUBLIC AUTODIFF_ENABLE_IMPLICIT_CONVERSION_REAL=1)
~~~

**Comment by allanleal** [comment]
Just a heads up. I see you defined your function `f` with `VectorXd` instead of `ArrayXreal`:

~~~c++
double f(const Eigen::VectorXd& x)
{
  return (x * x).sum();
}
~~~

Your function should be:

~~~c++
real f(const autodiff::ArrayXreal& x)
{
  return (x * x).sum();
}
~~~

Note also that `x * x` for an `Eigen::VectorXd` or `autodiff::VectorXreal` does not represent point-wise multiplication.

**Comment by joao-pm-santos96** [comment]
> Hi @joao-pm-santos96 , thanks for your feedback. This is most likely happening because you have not activated implicit conversion from autodiff numbers to `double`. By default, you have to do conversions explicitly.
> 
> Try define this before including autodiff header files::
> 
> ```c++
> define AUTODIFF_ENABLE_IMPLICIT_CONVERSION_REAL=1
> ```
> 
> or add this in your `CMakeList.txt` file:
> 
> ```
> target_compile_definitions(YourTargetName PUBLIC AUTODIFF_ENABLE_IMPLICIT_CONVERSION_REAL=1)
> ```

Thank you so much, this did in fact solve the compilation!

**Comment by joao-pm-santos96** [comment]
> Just a heads up. I see you defined your function `f` with `VectorXd` instead of `VectorXreal`:
> 
> ```c++
> double f(const Eigen::VectorXd& x)
> {
>   return (x * x).sum();
> }
> ```
> 
> Your function should be:
> 
> ```c++
> real f(const autodiff::VectorXreal& x)
> {
>   return (x * x).sum();
> }
> ```

Yes, that is actually the problem. Function `f` is just an example function. In reality I have a "black-box" function similar to that one (which I do not know exactly how it computes things...) that I want to differentiate.

What now is happening is that I am able to successufly compile and computr `u`, but the gradient is always zeros... Do I have any hope?

**Comment by allanleal** [comment]
`autodiff` does not work with functions that are black-box and have not been integrated with autodiff number types. You may have to resort to finite differences (not an ideal solution, potentially inaccurate, but your options are very limited).

**Comment by joao-pm-santos96** [comment]
Yeah that was what I feared... anyway, great work with the library and thank you for your time and help. :smile:
