### ISSUE TITLE
Multi Vector-variable Jacobian

### ISSUE THREAD

**Issue by AzureViolin** [autodiff/autodiff#29]
Previous discussion:
> Regarding the multi variable jacobian, I don't know how to add a new item to your tutorial.
> https://autodiff.github.io/tutorials/#jacobian-of-a-vector-function
> Specifically, I'd like to add a section after:
> 
> **Jacobian of a vector function**
> 
> And call it
> 
> **Jacobian of a multi-vector function**
> 
> Then attached with a section of code. Could you point me to which file I should change? I can then go ahead change it and do a PR.

> As to the tutorial, I propose we discuss this in a new issue. Would you please open a new issue and explain (briefly) about the tutorial (with explanation about this multi-vector function)?

The tutorial would essentially be just an example of how to compute a Jacobian of a multi vector-variable function, with the help of lambda.

```
VectorXdual g(const VectorXdual& x, const VectorXdual& v)
{
  Vector3dual vec_p;        vec_p << x(0), x(1), x(2);
  Vector3dual vec_o;        vec_o << x(3), x(4), x(5);
  Vector3dual vec_pv;       vec_pv<< x(6), x(7), x(8);
  Vector3dual measured_vel = R(vec_o).transpose() * vec_pv;
  VectorXdual g_value(9);   g_value << vec_p, vec_o, measured_vel;
  g_value = g_value + v;
  return g_value;
}

    VectorXdual x = eMU_t;
    VectorXdual v = VectorXd::Zero(Zt.size());
    auto gCt = [=](const VectorXdual& x) {return g(x, v); };
    auto gWt = [=](const VectorXdual& v) {return g(x, v); };
    VectorXdual g_value = g(x,v);

    MatrixXd Ct = autodiff::jacobian(gCt,g_value,x);
    MatrixXd Wt = autodiff::jacobian(gWt,g_value,v);
```
This is part of the code for implementing EKF. Essentially g(x,v) is the function, where both x and v are vector, and I want their corresponding jacobian. 

In the tutorial I'll clean up the code and make a easier one with complete variable definitions and stuff. 

Also, what is the type of gCt and gWt? auto is the only way I can get it to compile.

**Comment by AzureViolin** [comment]
Also, it probably should be done in a nicer way, just like how multi-variable derivative is done. This is more hacky and not really how it should be used.

**Comment by allanleal** [comment]
`auto` could possibly be replaced by `std::function<VectorXdual(const VectorXdual&)>` but I would rather stick with `auto`.

The tutorial should not have specific stuff, such as `measured_vel`. It would be nicer something simple, purely mathematical, like the other examples. For example:

~~~c++
VectorXdual f(const VectorXdual& x, const VectorXdual& y)
{
    return x.dot(x) * y.array().exp();
}
~~~

**Comment by allanleal** [comment]
Motivated by this usage requirement of yours, I'm re-implementing functions `gradient` and `jacobian` so that we can do:

~~~c++
const auto [F, J] = jacobian(f, x);
~~~

with the evaluation of `f` returned by `jacobian`, as vector `F`, to avoid an extra re-evaluation of `f` inside `jacobian`. There will also be an overload that permits the calculation of gradient and Jacobian with respect to only certain variables.

For example, to calculate the Jacobian matrix w.r.t. only the last 5 variables in `x`, we could do:

~~~c++
const auto [F, J] = jacobian(f, wrt(x.tail(5)), at(x));
~~~

For your specific case, you'll be able to write:


~~~c++
VectorXdual F;
MatrixXd Jx, Jy;

std::tie(F, Jx) = jacobian(f, wrt(x), at(x, y));
std::tie(F, Jy) = jacobian(f, wrt(y), at(x, y));
~~~

**Comment by allanleal** [comment]
You can follow the progress of this on this PR #30 .

**Comment by AzureViolin** [comment]
So I guess this issue should be closed now since there's a new way to use jacobian.

**Comment by allanleal** [comment]
Yes, thanks!
