### ISSUE TITLE
In-place std::transform on std::vector<autodiff::dual> does not work as expected

### ISSUE THREAD

**Issue by mennodeij** [autodiff/autodiff#354]
Find below a minimal reproduction of what the issue is. With MSVC this works, with g++ 13.2.0 under Ubuntu 24.04 (WSL2) it does not.
When the std::transform is replaced by a for-loop, the problem goes away.

output:
```
0.000177778
0.000177778
0.000177778
0.000177778
0.000177778

0.0133333
0.0533333
0.146667
0.293333
0.493333
```

I hope someone can explain why this happens, what am I doing wrong? Or is this something that needs fixing in autodiff?

```cpp
#include <iostream>
#include <numeric>
#include <algorithm>
#include "autodiff/forward/dual.hpp"
#include "autodiff/forward/dual/eigen.hpp"

template<typename T>
std::vector<T> Calculate(const Eigen::Array2<T>& uv)
{
        std::vector<T> result; result.reserve(5);
        for(int i = 0; i < 5; ++i){
                T item;
                item = uv(0)*(i+1) + uv(1)*std::pow(i,2);
                result.push_back(item);
        }
        T zero = 0.0;
        T sum = std::accumulate(result.begin(), result.end(), zero);
        // the following line is problematic
        std::transform(result.begin(), result.end(), result.begin(), [sum](T x) { return x/sum; });
        return result;

}

int main(void)
{
        Eigen::Array2dual uv;
        uv << 1, 2;
        uv(0).grad = 1.0;

        std::vector<autodiff::dual> x = Calculate(uv);
        for(auto& item : x)
                std::cout << item << std::endl;

        Eigen::Array2d st;
        st << 1, 2;

        std::vector<double> y = Calculate(st);
        for(auto& item : y)
                std::cout << item << std::endl;
}
```

**Comment by yut23** [comment]
Okay, I've figured out what's going wrong, with some help from AddressSanitizer. One important thing to understand is that the lambda currently returns an unevaluated expression, not `T` as might be expected. Since `x` is passed by value, it's actually a copy that goes out of scope at the end of the lambda, which leads to an invalid access when the expression is assigned to the elements of `result`.

The proper fix is to either pass `x` by reference in the lambda, or force the expression to be evaluated inside the lambda by specifying the return type as `T` or wrapping it in `autodiff::eval()`.

**Comment by mennodeij** [comment]
Apologies for my late comment - summer holidays ;)

If I understand correctly, I should replace this line
```
std::transform(result.begin(), result.end(), result.begin(), [sum](T x) { return x/sum; });
```
with 
```
std::transform(result.begin(), result.end(), result.begin(), [sum](T& x) { return x/sum; });
```

**Comment by yut23** [comment]
Yes, that should work in this case. However, if you have a more complicated lambda with conditional paths that return different things, compilation will fail since the returned expressions have different types:
```cpp
std::transform(result.begin(), result.end(), result.begin(), [sum](T& x) {
    if (x > 10) {
        return x/sum + 1; // return type is AddExpr<int, MulExpr<dual, InvExpr<dual>>>
    } else {
        return x/sum;     // return type is MulExpr<dual, InvExpr<dual>>
    }
});
```

Personally, I think specifying the return type is the cleanest solution in general, like so:
```cpp
std::transform(result.begin(), result.end(), result.begin(), [sum](T x) -> T { return x/sum; });
```

**Comment by mennodeij** [comment]
Thank you for your help with this.
