### ISSUE TITLE
Inaccuracies in the processing of a special case for a power function

### ISSUE THREAD

**Issue by AlexLiogky** [autodiff/autodiff#75]
Hello, thanks for developing a great math library.
Below I will describe the problem that I discovered and which seems to me to be a bug.  

    #include <iostream>
    #include <Eigen/Core>
    #include <autodiff/reverse.hpp>
    
    using namespace std;
    using namespace autodiff;
    
    var f1(var x)
    {
        return x*x;
    }
    
    var f2(var x)
    {
        return pow(x, 2);
    }
    
    int main(){
        var x = 0.0;                           // zero is special case but when power >= 1 derivative should exist
        var u1 = f1(x);                        // f1 = x * x
        var u2 = f2(x);                        // f2 = pow(x, 2)
    
        Derivatives dud1 = derivatives(u1);
        Derivatives dud2 = derivatives(u2);
    
        var dudx1 = dud1(x);
        var dudx2 = dud2(x);
    
        cout << "du/dx1 = " << dudx1 << endl;  // here du/dx = 0, that's OK
        cout << "du/dx2 = " << dudx2 << endl;  // but here du/dx = -nan, that's possible bug
    }

This simple program gives different results, although the functions are actually the same. Perhaps the problem is that I need an implementation of the function of raising to the INTEGER power, but I did not find it when I looked at the documentation fluently. However, in any case, in the zero argument with powers of at least 1, the derivative (at least one-sided) still exists and it would be nice to give it out.

**Comment by allanleal** [comment]
Hi, I can check this tomorrow morning. Can you post the different values please.

**Comment by AlexLiogky** [comment]
Thanks, I will wait this fix =)

**Comment by allanleal** [comment]
Hi @AlexLiogky . The issue here is that one needs to realize that `x*x` is not actually equivalent (functional speaking) to `pow(x, 2)`. Think of the latter as an actual [power function](https://en.wikipedia.org/wiki/Exponentiation#Power_functions) whose derivative is given below (considering also *x'* and *y'* as the derivatives of *x* and *y* respectively!):

![image](https://user-images.githubusercontent.com/5825588/68010550-30bc2f80-fc85-11e9-95b3-1b9d3552af63.png)

Note that the derivative is not defined when *x* is zero. 

Also note that `std::pow` does not have an overload for integer exponents in C++11. See [here](https://en.cppreference.com/w/cpp/numeric/math/pow). Usually, one wants to avoid `pow` in C++ for integer powers. Check [this benchmark](https://baptiste-wicht.com/posts/2017/09/cpp11-performance-tip-when-to-use-std-pow.html).

**Comment by AlexLiogky** [comment]
Thank you, I understand the origin of problem :), i will not use pow(...) for integer powers.
