### ISSUE TITLE
Implement ConditionExpr for reverse mode algorithm

### ISSUE THREAD

**Issue by allanleal** [autodiff/autodiff#88]
@ludkinm @supersega

This is a follow up of [this discussion](https://github.com/autodiff/autodiff/issues/40#issuecomment-554226543_). 

Consider the following function:

~~~c++
var f(var x) { return (x > 0) ? x**x : x*x*x; } 
~~~

Consider now what happens in the code below:

~~~c++
var x, u;

x = 1.0; 
u = f(x); // expression tree constructed for x*x

x = -1.0; 
u = f(x); // expression tree constructed for x*x*x
~~~

Each function call is re-constructing the expression tree. To be able to avoid this, we need a `ConditionExpr` and `condition` function, so that future evaluations of `u` could be done by just changing `x`, and then applying an update request on `u`, for example:

~~~c++
var f(var x) { return condition(x > 0, x**x, x*x*x); } 
~~~

which would permit us to do:

~~~c++
x = 1.0; 
u = f(x);

x = -1.0; 
u.update(); // this functionality also needs to be implemented
~~~

I think with this addition, will truly be able to no longer require expression tree reconstruction, which has happened so far because of potential branching in expressions involving `var` numbers.

_Originally posted by @allanleal in https://github.com/autodiff/autodiff/issues/40#issuecomment-554226543_

**Comment by jargonzombies** [comment]
I'm interested in this feature, but I'd need a bit of mentoring to get it done!

I had a go at implementing the conditional expression and the update functionality, but I've noticed that for your example code to work, two important things have to change:

First, the C++ expression `x > 0` (where `x` is a `var`) needs to become an `Expr<bool>` of its own instead of just a `bool`. That would be a breaking change. Is that okay? An alternate formulation with lambdas is possible instead, of course, and that's what I settled for so far.

Secondly, the assignment `x = -1.0;` currently creates a new independent variable. The `x` variables passed to the conditional are preserved however, so:
```c++
var x = 2.0;
var u = conditional(x > 0, x * x, x * x * x);
x = -2.0; // The 'x' copy in the expression tree in 'u' is unaffected
u.update(); // val(u) is still 4, and not -9
```

For your example to work, the semantics of value-assigning `Variable` would have to change, maybe like so:

```diff
@@ -1080,7 +1299,15 @@ struct Variable
 
     /// Assign an arithmetic value to this variable.
     template<typename U, EnableIf<isArithmetic<U>>...>
-    auto operator=(const U& val) -> Variable& { *this = Variable(val); return *this; }
+    auto operator=(const U& val) -> Variable& {
+      if(auto independentExpr = std::dynamic_pointer_cast<IndependentVariableExpr<T>>(expr)) {
+        independentExpr->val = val;
+        independentExpr->update();
+      } else {
+        *this = Variable(val);
+      }
+      return *this;
+    }
```

I personally think it's a bit awkward to make a distinction between independent and dependent variables here. Is there a better way forward?

**Comment by allanleal** [comment]
Hi @jargonzombies . It would be great if you could get this feature implemented. Why do we need to change `operator=` above?
